### ISSUE TITLE
Caret postion in contenteditable div

### ISSUE THREAD

**Issue by Jakobovski** [acdvorak/jquery.caret#2]
It would be really useful to be able to get the caret's position in a content-editable div that includes the length of the div's elements such as `&nbsp;` and `<br>`.

I would be happy to implement this feature.  Does anybody have an opinion on whether this would be an appropriate addition to jquery.caret?

**Comment by acdvorak** [comment]
Thanks for the suggestion!

#### Short answer

I have no desire to even _attempt_ such a feature, but if you can figure out how to make it work in every browser (IE8+), I would be happy to include it in jquery.caret.  Keep in mind, however, that it would need to work for every weird combination of elements you can think of (think nested `<table>`s and `float`ed `<span>`s and whatnot).

#### Long answer

I looked into getting/setting the caret position and selection range of non-`input` elements (`<div>`, `<span>`, etc.) a while back, but sadly it appears to be incredibly complicated, even in W3-compliant browsers like Chrome and Firefox.

`<input>` and `<textarea>` elements are (relatively) simple and straightforward; you only have a single, uninterrupted, linear stream of plain text.  What exactly would `.caret()` or `.range()` return when the user selects some text across portions of several `<td>` cells in a `<table>`, for example?  Dunno about you, but I have absolutely **no** idea -- and it sounds like a nightmare to implement (especially in IE).

If you can find a 100% bullet-proof method for getting/setting selection ranges on arbitrary DOM elements that's simple, intuitive, and easy to use, it would make a wonderful (and appropriate) addition to jquery.caret.  If not, you're probably better off starting your own library that does what you need.

(_**Side note**_: Although I'm not 100% sure, I would venture a semi-educated guess that `contenteditable` has very little to do with selection ranges.  `contenteditable` or not, the browsers' selection APIs _"should"_ be the same either way.)

**Comment by Jakobovski** [comment]
I started messing around with this idea and quickly realized how much of a nightmare this feature is to implement.  Thanks for the feedback!
